name = "BayesScoreCal"
uuid = "986b08a2-df14-4163-beea-1d3f6d344e0b"
authors = ["Joshua J Bon"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
